2025-05-23 16:48:27.620 [info] Extension host with pid 6680 started
2025-05-23 16:48:27.620 [info] Skipping acquiring lock for /home/dimgerasimou/.config/VSCodium/User/workspaceStorage/1882ba2a21686c8358f9e3d8dcde57e1.
2025-05-23 16:48:27.632 [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: false, activationEvent: 'onNotebookSerializer:jupyter-notebook'
2025-05-23 16:48:27.648 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2025-05-23 16:48:27.650 [info] ExtensionService#_doActivateExtension mhutchie.git-graph, startup: true, activationEvent: '*'
2025-05-23 16:48:27.663 [info] ExtensionService#_doActivateExtension ms-python.python, startup: true, activationEvent: 'workspaceContains:.venv'
2025-05-23 16:48:27.819 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2025-05-23 16:48:27.850 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2025-05-23 16:48:27.901 [info] ExtensionService#_doActivateExtension luma.jupyter, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-23 16:48:28.735 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-23 16:48:28.739 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-jupyter-cell-tags, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-23 16:48:28.741 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-jupyter-slideshow, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-23 16:48:28.932 [info] Eager extensions activated
2025-05-23 16:48:28.956 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
2025-05-23 16:48:29.085 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2025-05-23 16:48:29.088 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2025-05-23 16:48:29.106 [info] ExtensionService#_doActivateExtension Catppuccin.catppuccin-vsc, startup: false, activationEvent: 'onStartupFinished'
2025-05-23 16:48:29.112 [info] ExtensionService#_doActivateExtension Catppuccin.catppuccin-vsc-icons, startup: false, activationEvent: 'onStartupFinished'
2025-05-23 16:48:29.215 [info] ExtensionService#_doActivateExtension vadimcn.vscode-lldb, startup: false, activationEvent: 'onStartupFinished'
2025-05-23 16:48:29.321 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
2025-05-23 16:48:29.334 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-05-23 16:48:29.392 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-05-23 16:48:29.462 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2025-05-23 16:48:29.813 [info] ExtensionService#_doActivateExtension ms-python.debugpy, startup: false, activationEvent: 'onLanguage:python'
2025-05-23 16:56:47.896 [error] [ms-python.python] provider FAILED
2025-05-23 16:56:47.896 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 16:56:58.932 [error] [ms-python.python] provider FAILED
2025-05-23 16:56:58.933 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 16:56:59.999 [error] [ms-python.python] provider FAILED
2025-05-23 16:56:59.999 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 16:58:43.803 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:json'
2025-05-23 16:58:43.813 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onLanguage:json'
2025-05-23 17:36:58.980 [error] [ms-python.python] provider FAILED
2025-05-23 17:36:58.981 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 17:42:40.661 [error] [ms-python.python] provider FAILED
2025-05-23 17:42:40.661 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 17:46:00.448 [error] [ms-python.python] provider FAILED
2025-05-23 17:46:00.449 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:12:15.231 [error] [ms-python.python] provider FAILED
2025-05-23 19:12:15.232 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:12:15.486 [error] [ms-python.python] provider FAILED
2025-05-23 19:12:15.486 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:12:22.571 [error] [ms-python.python] provider FAILED
2025-05-23 19:12:22.571 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:12:23.573 [error] [ms-python.python] provider FAILED
2025-05-23 19:12:23.573 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:12:26.033 [error] [ms-python.python] provider FAILED
2025-05-23 19:12:26.033 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:12:27.575 [error] [ms-python.python] provider FAILED
2025-05-23 19:12:27.575 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:12:29.089 [error] [ms-python.python] provider FAILED
2025-05-23 19:12:29.090 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:12:36.061 [error] [ms-python.python] provider FAILED
2025-05-23 19:12:36.061 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:12:36.380 [error] [ms-python.python] provider FAILED
2025-05-23 19:12:36.380 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:12:37.058 [error] [ms-python.python] provider FAILED
2025-05-23 19:12:37.058 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:15:38.485 [error] [ms-python.python] provider FAILED
2025-05-23 19:15:38.486 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:31:59.293 [error] [ms-python.python] provider FAILED
2025-05-23 19:31:59.294 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:32:06.725 [error] [ms-python.python] provider FAILED
2025-05-23 19:32:06.725 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:32:14.969 [error] [ms-python.python] provider FAILED
2025-05-23 19:32:14.969 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:32:26.258 [error] [ms-python.python] provider FAILED
2025-05-23 19:32:26.258 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:32:48.889 [error] [ms-python.python] provider FAILED
2025-05-23 19:32:48.889 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:33:12.867 [error] [ms-python.python] provider FAILED
2025-05-23 19:33:12.867 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:33:15.987 [error] [ms-python.python] provider FAILED
2025-05-23 19:33:15.987 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:35:36.719 [error] [ms-python.python] provider FAILED
2025-05-23 19:35:36.719 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:35:40.960 [error] [ms-python.python] provider FAILED
2025-05-23 19:35:40.960 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 19:38:10.063 [info] ExtensionService#_doActivateExtension vscode.media-preview, startup: false, activationEvent: 'onCustomEditor:imagePreview.previewEditor'
2025-05-23 19:38:30.032 [error] [ms-python.python] provider FAILED
2025-05-23 19:38:30.032 [error] Error: ValueError: `column` parameter (26) is not in a valid range (0-25) for line 5 ('x = np.linspace(0, 10, 5)\n').
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-23 20:16:10.007 [info] Extension host terminating: renderer closed the MessagePort
2025-05-23 20:16:10.041 [info] Extension host with pid 6680 exiting with code 0
2025-05-23 20:16:10.492 [info] Extension host with pid 85057 started
2025-05-23 20:16:10.492 [info] Skipping acquiring lock for /home/dimgerasimou/.config/VSCodium/User/workspaceStorage/1882ba2a21686c8358f9e3d8dcde57e1.
2025-05-23 20:16:10.502 [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: false, activationEvent: 'onNotebookSerializer:jupyter-notebook'
2025-05-23 20:16:10.513 [info] ExtensionService#_doActivateExtension luma.jupyter, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-23 20:16:10.721 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-23 20:16:10.722 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-jupyter-cell-tags, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-23 20:16:10.723 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-jupyter-slideshow, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-23 20:16:10.725 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
2025-05-23 20:16:10.730 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-05-23 20:16:10.767 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-05-23 20:16:10.804 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2025-05-23 20:16:10.821 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.debugpy
2025-05-23 20:16:10.938 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'onRenderer:jupyter-notebook-renderer'
2025-05-23 20:16:10.939 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:json'
2025-05-23 20:16:10.947 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onLanguage:json'
2025-05-23 20:16:10.965 [info] ExtensionService#_doActivateExtension vscode.media-preview, startup: false, activationEvent: 'onCustomEditor:imagePreview.previewEditor'
2025-05-23 20:16:11.893 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2025-05-23 20:16:11.894 [info] ExtensionService#_doActivateExtension mhutchie.git-graph, startup: true, activationEvent: '*'
2025-05-23 20:16:11.959 [info] ExtensionService#_doActivateExtension ms-python.debugpy, startup: false, activationEvent: 'onLanguage:python'
2025-05-23 20:16:12.044 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2025-05-23 20:16:12.074 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2025-05-23 20:16:12.169 [info] Eager extensions activated
2025-05-23 20:16:12.185 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2025-05-23 20:16:12.186 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2025-05-23 20:16:12.199 [info] ExtensionService#_doActivateExtension Catppuccin.catppuccin-vsc, startup: false, activationEvent: 'onStartupFinished'
2025-05-23 20:16:12.202 [info] ExtensionService#_doActivateExtension Catppuccin.catppuccin-vsc-icons, startup: false, activationEvent: 'onStartupFinished'
2025-05-23 20:16:12.265 [info] ExtensionService#_doActivateExtension vadimcn.vscode-lldb, startup: false, activationEvent: 'onStartupFinished'
2025-05-23 20:21:08.231 [error] [ms-python.python] provider FAILED
2025-05-23 20:21:08.231 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-24 03:37:48.849 [info] Extension host terminating: renderer closed the MessagePort
2025-05-24 03:37:48.912 [info] Extension host with pid 85057 exiting with code 0
