2025-05-31 22:02:38.925 [info] Extension host with pid 389558 started
2025-05-31 22:02:38.925 [info] Skipping acquiring lock for /home/dimgerasimou/.config/VSCodium/User/workspaceStorage/7de870599db1a52e59f7d80982dcf6d8.
2025-05-31 22:02:38.943 [info] ExtensionService#_doActivateExtension vscode.configuration-editing, startup: false, activationEvent: 'onLanguage:jsonc'
2025-05-31 22:02:38.952 [info] ExtensionService#_doActivateExtension vscode.json-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-05-31 22:02:39.002 [info] ExtensionService#_doActivateExtension vscode.typescript-language-features, startup: false, activationEvent: 'onLanguage:jsonc'
2025-05-31 22:02:39.052 [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onLanguage'
2025-05-31 22:02:39.247 [info] ExtensionService#_doActivateExtension vscode.git-base, startup: true, activationEvent: '*', root cause: vscode.git
2025-05-31 22:02:39.251 [info] ExtensionService#_doActivateExtension mhutchie.git-graph, startup: true, activationEvent: '*'
2025-05-31 22:02:39.306 [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*'
2025-05-31 22:02:39.341 [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
2025-05-31 22:02:39.378 [info] Eager extensions activated
2025-05-31 22:02:39.401 [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: false, activationEvent: 'onStartupFinished'
2025-05-31 22:02:39.402 [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
2025-05-31 22:02:39.415 [info] ExtensionService#_doActivateExtension Catppuccin.catppuccin-vsc, startup: false, activationEvent: 'onStartupFinished'
2025-05-31 22:02:39.418 [info] ExtensionService#_doActivateExtension Catppuccin.catppuccin-vsc-icons, startup: false, activationEvent: 'onStartupFinished'
2025-05-31 22:02:39.483 [info] ExtensionService#_doActivateExtension vadimcn.vscode-lldb, startup: false, activationEvent: 'onStartupFinished'
2025-05-31 22:03:07.749 [info] ExtensionService#_doActivateExtension vscode.ipynb, startup: false, activationEvent: 'onCommand:ipynb.newUntitledIpynb'
2025-05-31 22:03:07.800 [info] ExtensionService#_doActivateExtension luma.jupyter, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-31 22:03:08.071 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-31 22:03:08.072 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-jupyter-cell-tags, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-31 22:03:08.073 [info] ExtensionService#_doActivateExtension ms-toolsai.vscode-jupyter-slideshow, startup: false, activationEvent: 'onNotebook:jupyter-notebook'
2025-05-31 22:03:08.230 [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
2025-05-31 22:03:08.359 [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
2025-05-31 22:03:09.274 [info] ExtensionService#_doActivateExtension ms-python.debugpy, startup: false, activationEvent: 'onLanguage:python'
2025-05-31 22:03:38.389 [info] ExtensionService#_doActivateExtension vscode.extension-editing, startup: false, activationEvent: 'onLanguage:markdown'
2025-05-31 22:03:38.402 [info] ExtensionService#_doActivateExtension vscode.markdown-language-features, startup: false, activationEvent: 'onLanguage:markdown'
2025-05-31 22:03:38.674 [info] ExtensionService#_doActivateExtension vscode.markdown-math, startup: false, activationEvent: 'api', root cause: vscode.markdown-language-features
2025-05-31 22:08:10.341 [info] ExtensionService#_doActivateExtension vscode.npm, startup: false, activationEvent: 'onLanguage:json'
2025-05-31 22:18:49.943 [error] [ms-python.python] provider FAILED
2025-05-31 22:18:49.943 [error] Error: IndexError: list index out of range
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:23:28.587 [error] [ms-python.python] provider FAILED
2025-05-31 22:23:28.587 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:23:28.889 [error] [ms-python.python] provider FAILED
2025-05-31 22:23:28.890 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:33:21.685 [error] [ms-python.python] provider FAILED
2025-05-31 22:33:21.685 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:36:54.738 [error] [ms-python.python] provider FAILED
2025-05-31 22:36:54.739 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:36:55.241 [error] [ms-python.python] provider FAILED
2025-05-31 22:36:55.241 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:53:08.847 [error] [ms-python.python] provider FAILED
2025-05-31 22:53:08.848 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:53:13.364 [error] [ms-python.python] provider FAILED
2025-05-31 22:53:13.364 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:55:09.651 [error] [ms-python.python] provider FAILED
2025-05-31 22:55:09.651 [error] Error: UnboundLocalError: cannot access local variable 'end_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:55:32.862 [error] [ms-python.python] provider FAILED
2025-05-31 22:55:32.862 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:55:40.421 [error] [ms-python.python] provider FAILED
2025-05-31 22:55:40.422 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:55:42.756 [error] [ms-python.python] provider FAILED
2025-05-31 22:55:42.756 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:55:43.116 [error] [ms-python.python] provider FAILED
2025-05-31 22:55:43.117 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 22:55:45.906 [error] [ms-python.python] provider FAILED
2025-05-31 22:55:45.906 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 23:39:48.703 [error] [ms-python.python] provider FAILED
2025-05-31 23:39:48.703 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 23:40:32.114 [error] [ms-python.python] provider FAILED
2025-05-31 23:40:32.114 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 23:40:32.984 [error] [ms-python.python] provider FAILED
2025-05-31 23:40:32.984 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 23:40:33.982 [error] [ms-python.python] provider FAILED
2025-05-31 23:40:33.982 [error] Error: UnboundLocalError: cannot access local variable 'start_index' where it is not associated with a value
    at ae (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1965471)
    at oe (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1963431)
    at Immediate.<anonymous> (/home/dimgerasimou/.vscode-oss/extensions/ms-python.python-2025.4.0-universal/out/client/extension.js:2:1959725)
    at processImmediate (node:internal/timers:483:21)
2025-05-31 23:46:37.727 [info] Extension host terminating: renderer closed the MessagePort
2025-05-31 23:46:37.790 [info] Extension host with pid 389558 exiting with code 0
